apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-nginx
  minReplicas: 2
  maxReplicas: 5
  metrics:
  #- type: Resource
  #  resource:
  #    name: cpu
  #    targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi

